include:
  - ./mocks/mock-oidc/compose.yml
  - ./mocks/mock-server/compose.yml

services:

#  backend:
##    backend spring boot inkludert  frontend som kjører på 8080
#    build: backend
#    ports:
#      - "8080:8080"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    environment:
#      AZURE_OPENID_CONFIG_ISSUER: http://host.docker.internal:8102/azure-mock
#      AZURE_APP_CLIENT_ID: historisk-superapp
#    env_file:
#      - path: ../../local.env
#        required: false
#
#  frontend:
#    # Proxy for frontend som kan skrues av for lokal utvikling med vite. Pekes på av wonderwall
#    image: alpine/socat
#    command:
#      "tcp-l:80,fork,reuseaddr tcp:wonderwall:4000"
#    ports:
#      - "3000:80"

  backend-proxy:
    # Proxy for backend som pekes på av wonderwall. Trengs for å unngå problemer med å skru backend av og på
    image: alpine/socat
    command:
      "tcp-l:80,fork,reuseaddr tcp:host.docker.internal:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  wonderwall:
    # Auth-proxy som lytter på 4000 og gir bearer token til backend-proxy
    image: ghcr.io/nais/wonderwall:latest
    command: >
      --auto-login=true
      --openid.client-id=historisk-superapp
      --openid.client-secret=not-so-secret
      --openid.well-known-url=http://host.docker.internal:8102/azure-mock/.well-known/openid-configuration
      --ingress=http://localhost:4000
      --bind-address=0.0.0.0:4000
      --upstream-host=backend-proxy:80
      --log-level=debug
      --log-format=text
    restart: on-failure
    ports:
      - "4000:4000"
    depends_on:
      - mock-oidc
      - backend-proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"

# https://github.com/nais/wonderwalled/blob/master/docker-compose.yml
  texas:
    image: ghcr.io/nais/texas:latest
    ports:
      - "4100:4100"
    environment:
      BIND_ADDRESS: "0.0.0.0:4100"
      AZURE_ENABLED: true
      # expected audience for user token from wonderwall
      AZURE_APP_CLIENT_ID: historisk-superapp
      # this key is useless in production; disregard security notices
      AZURE_APP_JWK: '{"p":"_LNnIjBshCrFuxtjUC2KKzg_NTVv26UZh5j12_9r5mYTxb8yW047jOYFEGvIdMkTRLGOBig6fLWzgd62lnLainzV35J6K6zr4jQfTldLondlkldMR6nQrp1KfnNUuRbKvzpNKkhl12-f1l91l0tCx3s4blztvWgdzN2xBfvWV68","kty":"RSA","q":"9MIWsbIA3WjiR_Ful5FM8NCgb6JdS2D6ySHVepoNI-iAPilcltF_J2orjfLqAxeztTskPi45wtF_-eV4GIYSzvMo-gFiXLMrvEa7WaWizMi_7Bu9tEk3m_f3IDLN9lwULYoebkDbiXx6GOiuj0VkuKz8ckYFNKLCMP9QRLFff-0","d":"J6UX848X8tNz-09PFvcFDUVqak32GXzoPjnuDjBsxNUvG7LxenLmM_i8tvYl0EW9Ztn4AiCqJUoHw5cX3jz_mSqGl7ciaDedpKm_AetcZwHiEuT1EpSKRPMmOMQSqcJqXrdbbWB8gdUrnTKZIlJCfj7yqgT16ypC43TnwjA0UwxhG5pHaYjKI3pPdoHg2BzA-iubHjVn15Sz7-pnjBmeGDbEFa7ADY-1yPHCmqqvPKTNhoCNW6RpG34Id9hXslPa3X-7pAhJrDBd0_NPlktSA2rUkifYiZURhHR5ijhe0v3uw6kYP8f_foVm_C8O1ExkxXh9Dg8KDZ89dbsSOtBc0Q","e":"AQAB","use":"sig","kid":"l7C_WJgbZ_6e59vPrFETAehX7Dsp7fIyvSV4XhotsGs","qi":"cQFN5q5WhYkzgd1RS0rGqvpX1AkmZMrLv2MW04gSfu0dDwpbsSAu8EUCQW9oA4pr6V7R9CBSu9kdN2iY5SR-hZvEad5nDKPV1F3TMQYv5KpRiS_0XhfV5PcolUJVO_4p3h8d-mo2hh1Sw2fairAKOzvnwJCQ6DFkiY7H1cqwA54","dp":"YTql9AGtvyy158gh7jeXcgmySEbHQzvDFulDr-IXIg8kjHGEbp0rTIs0Z50RA95aC5RFkRjpaBKBfvaySjDm5WIi6GLzntpp6B8l7H6qG1jVO_la4Df2kzjx8LVvY8fhOrKz_hDdHodUeKdCF3RdvWMr00ruLnJhBPJHqoW7cwE","alg":"RS256","dq":"IZA4AngRbEtEtG7kJn6zWVaSmZxfRMXwvgIYvy4-3Qy2AVA0tS3XTPVfMaD8_B2U9CY_CxPVseR-sysHc_12uNBZbycfcOzU84WTjXCMSZ7BysPnGMDtkkLHra-p1L29upz1HVNhh5H9QEswHM98R2LZX2ZAsn4bORLZ1AGqweU","n":"8ZqUp5Cs90XpNn8tJBdUUxdGH4bjqKjFj8lyB3x50RpTuECuwzX1NpVqyFENDiEtMja5fdmJl6SErjnhj6kbhcmfmFibANuG-0WlV5yMysdSbocd75C1JQbiPdpHdXrijmVFMfDnoZTQ-ErNsqqngTNkn5SXBcPenli6Cf9MTSchZuh_qFj_B7Fp3CWKehTiyBcLlNOIjYsXX8WQjZkWKGpQ23AWjZulngWRektLcRWuEKTWaRBtbAr3XAfSmcqTICrebaD3IMWKHDtvzHAt_pt4wnZ06clgeO2Wbc980usnpsF7g8k9p81RcbS4JEZmuuA9NCmOmbyADXwgA9_-Aw"}'
      AZURE_OPENID_CONFIG_ISSUER: http://host.docker.internal:8102/azure-mock
      AZURE_OPENID_CONFIG_TOKEN_ENDPOINT: http://host.docker.internal:8102/azure-mock/token
      AZURE_OPENID_CONFIG_JWKS_URI: http://host.docker.internal:8102/azure-mock/jwks

    restart: on-failure
#    env_file: "${ENV_FILE:-.env}"
    extra_hosts:
      # See explanation in the wonderwall service
      - localhost:host-gateway
      - "host.docker.internal:host-gateway"