apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: superhelt
  namespace: historisk
  labels:
    team: historisk
spec:
  image: "{{image}}"
  port: 8080
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - NAVident

  liveness:
    path: /actuator/health/liveness
  readiness:
    path: /actuator/health/readiness
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 512Mi
  strategy:
    type: RollingUpdate
  replicas:
    min: 1
    max: 1

  prometheus:
    enabled: true
    path: /actuator/prometheus

  ingresses:
    - {{appIngress}}

  observability:
    autoInstrumentation:
      enabled: true
      runtime: sdk
