spring:
  application:
    name: super
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER}
#          audiences: ${AZURE_APP_CLIENT_ID}
  web:
    resources:
      static-locations:
        - classpath:/static

  jpa:
    open-in-view: false
